export interface social {
  airbnb: string,
  amazon: string,
  apple: string,
  booking: string,
  call: string,
  discord: string,
  ebay: string,
  email: string,
  facebook: string,
  facebookMessenger: string,
  foursquare: string,
  google: string,
  googleplus: string,
  instagram: string,
  linkedin: string,
  magento: string,
  medium: string,
  note: string,
  pinterest: string,
  prestashop: string,
  reddit: string,
  skype: string,
  slack: string,
  slideshare: string,
  sms: string,
  snapchat: string,
  soundcloud: string,
  steam: string,
  telegram: string,
  tumblr: string,
  twilio: string,
  twitch: string,
  twitter: string,
  vimeoBlue: string,
  vine: string,
  vk: string,
  webchat: string,
  whatsapp: string,
  woocommerce: string,
  wordpress: string,
  yahoo: string,
  youtube: string,
  zendesk: string,
}

declare const social: social;
export default social;
